// All Articles API
export const REQUEST_API_ARTICLES = 'REQUEST_API_ARTICLES';
export const RECEIVE_API_ARTICLES = 'RECEIVE_API_ARTICLES';

// Topics API
export const REQUEST_API_TOPICS = 'REQUEST_API_TOPICS';
export const RECIEVE_API_TOPICS = 'RECIEVE_API_TOPICS';

// Follow / Unfollow Topics
export const FOLLOW_TOPIC = 'FOLLOW_TOPIC';
export const UNFOLLOW_TOPIC = 'UNFOLLOW_TOPIC';
export const FOLLOW_ALL_TOPICS = 'FOLLOW_ALL_TOPICS';

// Single article API
export const REQUEST_SINGLE_ARTICLE = 'REQUEST_SINGLE_ARTICLE';
export const RECIEVE_SINGLE_ARTICLE = 'RECIEVE_SINGLE_ARTICLE';
export const CLEAR_SELECTED_ARTICLE = 'CLEAR_SELECTED_ARTICLE';
